language: node_js
node_js: 8

script:
- npm test
- npm run lint
- npm run nsp

branches:
  only:
  - master

deploy:
  provider: npm
  email: billing.media@schibsted.media
  on:
    branch: master
    node: '8'
  api_key:
    secure: gnmPjwifkFqZ0UiD3wRsPReZvlchJ+bKXBBRlq8/AxtylkMfho71TeUhNYd3k+jgzDF99XxDW3vXU/ysV9v/QqOGDh+0zOscxk72j2EUS4fcrYbf280zqzUdeFrETkqrAvXHMnFMI/gWA0NwMtHCM/4vyV0stsPs0bMwGVP3Zy514T816lK/xy2vlhsvSR3zYpRQ4s8DkHyhhzUFz2gSU37Lnjk+kf5KvOJmEnQv7kd5aVGry5/6qjrkvrj00pKtfaCEwnf04xykp4v1YpnfntYg5fDf3SdOF2p2QXcxg0NwF6szjuAYypNgO+Msau8h+J1PoJcxdY34kG9bOIJuBI40cGeOmlcftfm1t4HwCyooOOzKj4YwOWZTOVOK41T/byE1dijtnVVScXumnbTzoYX2V7F4ZIdy10twt/nmmae883tQi+a4OY+1NP0DczmdLGOR4MB5hFsXz8OFgtJkJ7Ef+Eh3WJqUNB/XnGqTR7+x68yOv9160PVIiqZznN5q4NQkj2XjqITl0AP9SGhk7L0+QwNsmnbs+0DbkRsJVhVPqBDmzlC73wIDin3mwxkfZsmyxnk6GxJby8/06SuHdEiOBDSL/NoL4FM/UnQoGpU2N7nq9MbQU+rfNtkM7n2yhlOfmhuWc42pYwcGyKqoihh3fwhqBYSoRYTCmbmMRdg=
